name: first-workflow
on: 
  push:
    branches:
      - main

jobs:
  examole-jops:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome massage
        run: echo "welcome to our first GitHub-action"
